rcon:
  host: "127.0.0.1"
  port: 25575

paths:
  backup_path: "/path/to/backups"
  world_path: "/path/to/World"
  log_path: "/path/to/logs/latest.log"

telegram:
  chat_id: 11111111111
  authorized_user_ids:
    - 11111111111
